plugins {
    id 'com.android.application'
}

android {
    namespace 'com.centrallite.dashboard'
    compileSdk 34

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    defaultConfig {
        applicationId "com.centrallite.dashboard"
        minSdk 21
        targetSdk 28
        versionCode 8
        versionName "0.7.1"
    }
}


dependencies {
    implementation 'org.osmdroid:osmdroid-android:6.1.20'
}
